services:
  navpilot:
    build:
      context: .
      dockerfile: Dockerfile
    image: navpilot_image
    container_name: navpilot_container

    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    # ...or legacy runtime flag:
    runtime: nvidia

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video,graphics,display
      - DISPLAY=${DISPLAY:-:0}
      - OPEN3D_RENDERING_BACKEND=glsl

    volumes:
      - ./workspace:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev

    ports:
      - "8765:8765"

    tty: true
    stdin_open: true
    privileged: true
    security_opt:
      - seccomp:unconfined
    shm_size: 40g