waypoints_routing_node:
  ros__parameters:
    map_path: "/workspace/navpilot_ws/src/hdmap_stack/hdmap_visualizer/osms/1_new66.osm"
    start_lanelet_id: 3848
    end_lanelet_id: 31
    show_full_graph: true
    waypoint_interval: 3.0

osm_visualizer:
  ros__parameters:
    map_path: "/workspace/navpilot_ws/src/hdmap_stack/hdmap_visualizer/osms/1_new66.osm"
    occupancy_output_topic: "occupancy_grid_complete_map"
    resolution: 0.2
    close_radius: 1
    close_iters: 1
    outside_value: 100
    frame_id: "map"
