path_planning_node:
  ros__parameters:
    maxSteerAngle: 0.7
    wheelBase: 2.75
    axleToFront: 1.1
    axleToBack: 1.2
    width: 1.9
    white_square_length: 3.0 # meters, along vehicle (forward/back)
    white_square_width: 3.0 # meters, lateral (left/right)
    pathLength: 3
    step_car: 0.2
    tree_depth: 15
    branching_factor: 5
    type_map: "polygon" # "lanelet2" or "polygon"
    map_path: "/workspace/models/incmty.osm"
    polygon_path: "/workspace/models/hdmap_export.json"
    start_lanelet_id: 21
    end_lanelet_id: 28
    x_offset: 0.0
    y_offset: 0.0
    num_lateral_offsets: 0
    global_planner_resolution: 0.2
    global_planner_close_radius: 1
    global_planner_close_iters: 1
    global_planner_outside_value: 100
    global_planner_frame_id: "map"
    global_planner_occupancy_output_topic: "global_planner_occupancy_grid"
