path_planning_node:
  ros__parameters:
    maxSteerAngle: 0.6
    wheelBase: 2.75
    axleToFront: 1.1
    axleToBack: 1.2
    width: 1.9
    pathLength: 3
    step_car: 0.3
    tree_depth: 13
    branching_factor: 5
    map_path: "/workspace/navpilot_ws/src/hdmap_stack/hdmap_visualizer/osms/1_new66.osm"
    start_lanelet_id: 3848
    end_lanelet_id: 31
    x_offset: 0.0
    y_offset: 25.0
