path_planning_node:
  ros__parameters:
    maxSteerAngle: 0.6
    wheelBase: 2.75
    axleToFront: 1.1
    axleToBack: 1.2
    width: 1.9
    pathLength: 3
    step_car: 0.2
    tree_depth: 15
    branching_factor: 5
    map_path: "/workspace/oms/me_4.osm"
    start_lanelet_id: 206
    end_lanelet_id: 295
    x_offset: 0.0
    y_offset: 0.0
    num_lateral_offsets: 0
